name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  setup-linux-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ubuntu-desktop xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        # Allow RDP traffic on port 3391
        sudo sed -i 's/3389/3391/g' /etc/xrdp/xrdp.ini
        sudo systemctl restart xrdp
        sudo ufw allow 3391/tcp
        
    - name: Create and Configure RDP User
      run: |
        sudo useradd -m rdpuser -s /bin/bash
        echo "rdpuser:P@ssw0rd!" | sudo chpasswd
        sudo adduser rdpuser sudo

    - name: Configure GNOME for XRDP
      run: |
        echo "gnome-session" > ~/.xsession
        sudo systemctl restart xrdp
        
    - name: Start SSH Tunnel for Linux RDP
      shell: bash
      run: |
        echo "Starting SSH tunnel for Linux RDP..."
        ssh -o StrictHostKeyChecking=no -T -R 3391:localhost:3391 serveo.net > serveo_output.txt 2>&1 &
        sleep 10  # Allow time for the tunnel to establish
        cat serveo_output.txt

    - name: Simulate Stuck Behavior for 1 Day
      run: |
        echo "Simulating stuck tunnel for 1 Day..."
        sleep 86400

  setup-windows-rdp:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        # Enable Remote Desktop and configure firewall
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Set up RDP user account
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Start Serveo Tunnel for Windows RDP
      shell: bash
      run: |
        echo "Starting Serveo tunnel for Windows RDP..."
        # Start Serveo tunnel in the background
        ssh -o StrictHostKeyChecking=no -T -R 3388:localhost:3389 serveo.net > serveo_output.txt 2>&1 &
        sleep 10  # Allow time for the tunnel to establish
        # Output the Serveo tunnel URL for verification
        cat serveo_output.txt

    - name: Simulate Stuck Behavior for 1 Day
      run: |
        Write-Host "Simulating stuck tunnel for 1 Day..."
        Start-Sleep -Seconds 86400
